UPDATE `nextbook`.`subcategory` SET `name_en` = 'Gift Books' WHERE `id` = 1;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Albums' WHERE `id` = 2;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'VIP Gift Books' WHERE `id` = 3;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Arts' WHERE `id` = 4;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Culture' WHERE `id` = 5;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Architecture' WHERE `id` = 6;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Sculpture' WHERE `id` = 7;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Music' WHERE `id` = 8;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Notes' WHERE `id` = 9;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Cinematography' WHERE `id` = 10;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Photography' WHERE `id` = 11;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Theatre' WHERE `id` = 12;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Guseums' WHERE `id` = 13;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Galleries' WHERE `id` = 14;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Cultural monuments' WHERE `id` = 15;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Fine arts' WHERE `id` = 16;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Nonfiction' WHERE `id` = 17;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Biographies' WHERE `id` = 18;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Memoirs' WHERE `id` = 19;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Journalism' WHERE `id` = 20;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Special literature in foreign languages' WHERE `id` = 21;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Fiction in foreign languages' WHERE `id` = 22;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Foreign Literature' WHERE `id` = 23;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Business' WHERE `id` = 24;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Accounting and Auditing' WHERE `id` = 25;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Management' WHERE `id` = 26;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'MBA' WHERE `id` = 27;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Books of famous businessmen' WHERE `id` = 28;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Marketing' WHERE `id` = 29;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Advertising and PR' WHERE `id` = 30;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Finance' WHERE `id` = 31;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Economics and economic theory' WHERE `id` = 32;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Entrepreneurship' WHERE `id` = 33;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Business Psychology (Trainings)' WHERE `id` = 34;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Sales techniques' WHERE `id` = 35;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Banking' WHERE `id` = 36;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Juridical literature' WHERE `id` = 37;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Law literature of other areas' WHERE `id` = 38;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Children\'s Books' WHERE `id` = 39;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Children\'s novels and short stories' WHERE `id` = 40;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Fairy tales' WHERE `id` = 41;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Poetry for children' WHERE `id` = 42;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Children\'s fantasy and science fiction' WHERE `id` = 43;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Adventures' WHERE `id` = 44;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'children\'s detective and horror books' WHERE `id` = 45;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Books for the youngest' WHERE `id` = 46;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Coloring and crafts' WHERE `id` = 47;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Children\'s encyclopedia' WHERE `id` = 48;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Parents and tutors' WHERE `id` = 49;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Child Psychology' WHERE `id` = 50;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Child Health' WHERE `id` = 51;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Parenting' WHERE `id` = 52;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Computer Books' WHERE `id` = 53;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Graphics' WHERE `id` = 54;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Audio' WHERE `id` = 55;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Video' WHERE `id` = 56;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Computer architecture' WHERE `id` = 57;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Office software and advices to users' WHERE `id` = 58;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Operating Systems' WHERE `id` = 59;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Programming' WHERE `id` = 60;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Computer Security' WHERE `id` = 61;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Internet' WHERE `id` = 62;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Networks' WHERE `id` = 63;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Food' WHERE `id` = 64;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Beverages' WHERE `id` = 65;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Books for training and development' WHERE `id` = 66;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Textbooks' WHERE `id` = 67;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Language' WHERE `id` = 68;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Philology' WHERE `id` = 69;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Books for education' WHERE `id` = 70;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Pedagogy and methodology' WHERE `id` = 71;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Ethics and etiquette' WHERE `id` = 72;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Educational Juridical literature' WHERE `id` = 73;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Natural sciences' WHERE `id` = 74;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Mathematics' WHERE `id` = 75;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Statistics' WHERE `id` = 76;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Analysis' WHERE `id` = 77;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Physics' WHERE `id` = 78;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Astrology' WHERE `id` = 79;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Special technical literature' WHERE `id` = 80;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Science Fiction' WHERE `id` = 81;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Fantasy' WHERE `id` = 82;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Native fiction and fantasy of neighboring countries' WHERE `id` = 83;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Science fiction of foreign countries' WHERE `id` = 84;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Fiction' WHERE `id` = 85;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Native classics' WHERE `id` = 86;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Modern prose of native authors' WHERE `id` = 87;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Foreign classics' WHERE `id` = 88;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Modern foreign prose' WHERE `id` = 89;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Detective' WHERE `id` = 90;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Action' WHERE `id` = 91;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Crime' WHERE `id` = 92;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Classic detective' WHERE `id` = 93;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Modern detective' WHERE `id` = 94;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Ironic detective' WHERE `id` = 95;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Horror' WHERE `id` = 96;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Mystery' WHERE `id` = 97;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Thriller' WHERE `id` = 98;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Poetry' WHERE `id` = 99;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Lyrics' WHERE `id` = 100;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Sentimental novels' WHERE `id` = 101;
UPDATE `nextbook`.`subcategory` SET `name_en` = ' Historical novel' WHERE `id` = 102;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Pregnancy' WHERE `id` = 103;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Childbirth' WHERE `id` = 104;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Image and Beauty' WHERE `id` = 105;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Martial Arts' WHERE `id` = 106;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Dancing' WHERE `id` = 107;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Sex and erotic' WHERE `id` = 108;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Health' WHERE `id` = 109;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Herbal medicine' WHERE `id` = 110;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Yoga' WHERE `id` = 111;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Massage' WHERE `id` = 112;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Healthy eating' WHERE `id` = 113;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Diet' WHERE `id` = 114;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Alternative medicine and rehabilitation' WHERE `id` = 115;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Medicine and pharmacology' WHERE `id` = 116;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Legends' WHERE `id` = 117;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Epics' WHERE `id` = 118;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Ancient literature' WHERE `id` = 119;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Mythology' WHERE `id` = 120;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Mysteries of civilizations' WHERE `id` = 121;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'history' WHERE `id` = 122;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'History of Ukraine' WHERE `id` = 123;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'World history' WHERE `id` = 124;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Archeology' WHERE `id` = 125;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Civilizations' WHERE `id` = 126;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Ethnography' WHERE `id` = 127;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'History of Arts' WHERE `id` = 128;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Feng Shui' WHERE `id` = 129;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Housekeeping' WHERE `id` = 130;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Plants' WHERE `id` = 131;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Floristry' WHERE `id` = 132;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Garden' WHERE `id` = 133;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Vegetable garden' WHERE `id` = 134;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Interior design and landscaping' WHERE `id` = 135;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Pets' WHERE `id` = 136;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Livestock' WHERE `id` = 137;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Construction and repair' WHERE `id` = 138;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Tips for car enthusiasts' WHERE `id` = 139;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Special services' WHERE `id` = 140;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Weapons and military equipment' WHERE `id` = 141;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Warfare' WHERE `id` = 142;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Dictionaries' WHERE `id` = 143;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Encyclopedias' WHERE `id` = 144;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Atlases' WHERE `id` = 145;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Maps' WHERE `id` = 146;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'City maps of the world' WHERE `id` = 147;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Atlases of Ukraine' WHERE `id` = 148;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'World atlases' WHERE `id` = 149;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Reference books' WHERE `id` = 150;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Phrase Books' WHERE `id` = 151;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Dictionaries' WHERE `id` = 152;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Tourist Guides' WHERE `id` = 153;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Tips and tricks' WHERE `id` = 154;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Religion' WHERE `id` = 155;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Esoteric' WHERE `id` = 156;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Occult sciences' WHERE `id` = 157;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'History of Religions' WHERE `id` = 158;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Esoteric' WHERE `id` = 159;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Magic' WHERE `id` = 160;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Occult' WHERE `id` = 161;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Prophecy' WHERE `id` = 162;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Hobbies' WHERE `id` = 163;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Collectibles' WHERE `id` = 164;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Leisure' WHERE `id` = 165;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Sport' WHERE `id` = 166;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Fishing' WHERE `id` = 167;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Games' WHERE `id` = 168;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Entertainment' WHERE `id` = 169;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'DIY' WHERE `id` = 170;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Hunting' WHERE `id` = 171;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Aphorisms' WHERE `id` = 172;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Quotes and proverbs' WHERE `id` = 173;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Toasts' WHERE `id` = 174;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Congratulations and anecdotes' WHERE `id` = 175;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Holidays' WHERE `id` = 176;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Humor and Satire' WHERE `id` = 177;
UPDATE `nextbook`.`subcategory` SET `name_en` = 'Interpretation of Dreams' WHERE `id` = 178;
