-- MySQL Script generated by MySQL Workbench
-- 06/26/15 17:27:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema NextBook
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NextBook
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NextBook` DEFAULT CHARACTER SET utf8 ;
USE `NextBook` ;

-- -----------------------------------------------------
-- Table `NextBook`.`ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NextBook`.`ROLE` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NextBook`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NextBook`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `active` TINYINT(1) NULL DEFAULT true COMMENT '',
  `role_id` INT NULL COMMENT '',
  `Usercol` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `email_UNIQUE` (`email` ASC)  COMMENT '',
  INDEX `user_to_role_idx` (`role_id` ASC)  COMMENT '',
  CONSTRAINT `user_to_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `NextBook`.`ROLE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NextBook`.`PERMISSIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NextBook`.`PERMISSIONS` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `name_UNIQUE` (`name` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NextBook`.`ROLE_PERMISSIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `NextBook`.`ROLE_PERMISSIONS` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `role_id` INT NOT NULL COMMENT '',
  `permission_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `role_to_permission_idx` (`role_id` ASC)  COMMENT '',
  INDEX `permission_to_role_idx` (`permission_id` ASC)  COMMENT '',
  CONSTRAINT `role_to_permission`
    FOREIGN KEY (`role_id`)
    REFERENCES `NextBook`.`ROLE` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `permission_to_role`
    FOREIGN KEY (`permission_id`)
    REFERENCES `NextBook`.`PERMISSIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
